"""Generate the private exam deployment cache from the canonical QBank manifest.
No question authoring here. Invalid rows and duplicate content are reported, not repeated.
"""
import hashlib,json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parent.parent

def build():
    manifest=json.loads((ROOT/'data/pyq/manifest.json').read_text())
    paths=manifest if isinstance(manifest,list) else manifest['files']
    accepted=[]; seen=set(); ids=set(); rejected=[]
    for path in paths:
        for q in json.loads((ROOT/path).read_text()):
            ident=q.get('external_id'); opts=q.get('options',[])
            stem=re.sub(r'\W+',' ',q.get('stem','').lower()).strip()
            fingerprint=hashlib.sha256(stem.encode()).hexdigest()
            if not ident or not stem or len(opts)!=4 or len({o.get('label') for o in opts})!=4 or sum(o.get('is_correct') is True for o in opts)!=1 or any(not o.get('text','').strip() for o in opts) or ident in ids or fingerprint in seen:
                rejected.append(ident);continue
            ids.add(ident);seen.add(fingerprint)
            content={**q,'id':ident,'correct':next(o['label'] for o in opts if o.get('is_correct')),
                'options':[{'label':o['label'],'text':o['text']} for o in opts],
                'exam_type':q.get('exam_type') or ('Clinical Integration' if q.get('is_clinical') and q.get('is_integrated') else 'Clinical' if q.get('is_clinical') else 'Direct Recall'),
                'image':q.get('image_url') or q.get('image')}
            accepted.append((ident,fingerprint,content))
    revision=hashlib.sha256(json.dumps(accepted,sort_keys=True).encode()).hexdigest()
    quote=lambda s:"'"+s.replace("'","''")+"'"
    statements=['-- Generated by scripts/build_exam_bank.py; source: data/pyq manifest.','update exam_private.bank set enabled=false;']
    for ident,fp,c in accepted:
        statements.append('insert into exam_private.bank(id,fingerprint,content,source_revision,enabled) values ('+','.join([quote(ident),quote(fp),quote(json.dumps(c)),quote(revision),'true'])+') on conflict(id) do update set fingerprint=excluded.fingerprint,content=excluded.content,source_revision=excluded.source_revision,enabled=true;')
    return '\n'.join(statements),{'accepted':len(accepted),'rejectedDuplicatesOrMalformed':rejected,'revision':revision}

if __name__=='__main__':
    sql,report=build();(ROOT/'supabase/exam-bank.sql').write_text(sql+'\n');print(json.dumps(report,indent=2))
